language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # cppcheck
  - sudo apt-get install -qq cppcheck

script: 
  # Build and run this project
  - qmake
  - make
  - ./travis_qmake_gcc_cpp14_cppcheck
  # cppcheck (mild)
  - cppcheck --quiet . 
  # cppcheck that makes the Travis build fail
  #- cppcheck --quiet --error-exitcode=1 . 